# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: eozelius
  password: 'miraFlores7&'

development:
  adapter: postgresql
  database: imil_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: imil_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: imil_production
  pool: 5
  timeout: 5000