default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: asdf
  password: asdf

development:
  adapter: postgresql
  database: imil_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: imil_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d2dpbdj17k7lmf
  pool: 5
  timeout: 5000
  host: ec2-107-20-141-145.compute-1.amazonaws.com
  port: 5432
  user: ulcksmxcgxifto
  password: 6b02bc2b7ed25ffe7c34f021afa6f2fd31bfa37e6612c252a6c525300782ec35